test:
  trainer: DENetTrainer
  device: 3
  ckpt: runs
  id: reproduce_denet_coco_fold3_200k
  best: True
model:
  arch:  DENet
  backbone: ResNet50
  maximum_num_classes: 81
data:
  path: /home/liulizhao/datasets/COCO
  dataset: WrappedCOCOStuff20i
  fold: 3
  way: 1
  shot: 5
  img_size: 321
  batch_size: 20

# test script: python -u test.py --config config/test_denet_coco_fold3_1way_5shot.yml