test:
  trainer: DENetTrainer
  device: 0
  ckpt: runs
  id: reproduce_denet_coco_fold0_200k
  best: True
model:
  arch:  DENet
  backbone: ResNet50
  maximum_num_classes: 81
data:
  path: <your_path_to_COCO>
  dataset: WrappedCOCOStuff20i
  fold: 0
  way: 1
  shot: 5
  img_size: 321
  batch_size: 20

# test script: python -u test.py --config config/test_denet_coco_fold0_1way_5shot.yml